### PR TITLE
prepare 4.0.0 release

### PR DESCRIPTION
**Pull request by LaunchDarklyCI**
### Added:
- API support for approval settings at the environment level.
- API support for comment-style approval request reviews.
- `FeatureFlagApprovalRequestId`
- `FeatureFlagApprovalRequestPostRequest`
- `FeatureFlagApprovalRequestReviewPostRequest`
- `FeatureFlagApprovalRequestApplyPostRequest`

## Removed:
- `FeatureFlagChangeRequestId` 
- `FeatureFlagChangeRequestPostRequest`
- `FeatureFlagChangeRequestReviewPostRequest`
- `FeatureFlagChangeRequestApplyPostRequest`

### CODE REVIEW

**Review by tracisiebel — APPROVED** [review]
to @bwoskow-ld's point - i think you should add a
> “Removed” section since some of the apis were removed when they were renamed. 

Otherwise looks good!

**Review by bwoskow-ld — APPROVED** [review]

**Comment by goyanespaula** [comment]
> > “Removed” section since some of the apis were removed when they were renamed.

Done!

**Comment by goyanespaula** [comment]
Note: Verified the `lastActive` portion with @apucacao

**Comment by goyanespaula** [comment]
Closing this PR because the member API changes are not ready to go out. Opening a new one with just the approvals changes.

**Pull request closed without merging**
