### PR TITLE
npm audit fix and version bump.

### PR DESCRIPTION
**Pull request by Tim-LaunchDarkly**
I'm not sure if running npm audit fix a few times and bumping the webpack version is the correct tactic here to resolve the vulnerability thing we just got on this, but yarn test seems to pass so :shrug: 

Thoughts?

### CODE REVIEW

**Comment by eli-darkly** [comment]
Could you describe what the problem was?

**Comment by Tim-LaunchDarkly** [comment]
image
Was just trying to resolve those problems- various packages that have vulnerabilities in them.

**Comment by eli-darkly** [comment]
OK, well, I'm not sure what you're asking about when you say "Thoughts?". Without knowing what the specific problems were, I can't know whether this PR is the right way to fix them.

I do think it matters much less in this particular project (compared to for instance the SDKs) if we have a problematic npm dependency, or how we choose to fix it. This code does not interact with the outside world directly and is not run by customers; it's just a tool to take one set of files and generate another set of files. The files it generates _do_ get run by customers (potentially), but they have their own set of dependencies which are unrelated to the npm packages shown here.

**Comment by Tim-LaunchDarkly** [comment]
I was just hesitant to commit code on something I don't have a lot of familiarity on and was looking for some re-assurance that I wasn't going to bust something important without review. It seemed rather straightforward to simply bump the versions to where the XSS vulnerabilities got resolved and the test suite seemed to run fine, but I didn't know if there were special considerations that I didn't know about that wasn't covered in the test suite.

It sounds like it should be fine based on your comment so I'll go ahead with the merge.

**Comment by eli-darkly** [comment]
That's fine. Unfortunately we don't really have a test suite for this, but I don't think these changes are likely to break anything. We will find out next time we try to generate revised API clients.

**Pull request merged**
